image: node:11.15.0

cache:
  paths:
    - node_modules/

stages:
  - test

# test:
#   stage: test
#   script: 
#     - npm install
#     - cd client
#     - npm run build

build:
  stage: test
  before_script:


  script:
    - echo $SSH_PRIVATE_KEY >> key.pem
    - chmod 400 key.pem
    - ssh -i key.pem shiromdk@alannguyen.info
    - cd alannguyen.info  
    - npm install
    - cd client && npm run build
    - pm2 restart 0