image: node:11.15.0

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

test:
  stage: test
  script: 
    - npm install
    - cd client
    - npm run build

build:
  stage: build
  script:
    - echo "$PASSWORD" | ssh shiromdk@alannguyen.info --password-stdin
    - cd alannguyen.info  
    - npm install
    - cd client && npm run build
    - pm2 restart 0